### PR TITLE
Refactor Scaffold Generator.

### PR DESCRIPTION
**Pull request by azemoh**
Hi guys @thebrianemory @achasveachas,

To continue Yechielk's good work on the `ScaffoldGenerator`, I refactored the code a little bit to make things modular. Instead of copying everything from the `ModelGenerator` I am calling it programmatically `ModelGenerator.new([name, attributes]).invoke_all`. The current interface is not affected and everything works normally.

In the same spirit I think we should introduce a `ControllerGenerator` so we can also move the controller and views code out of the `ScaffoldGenerator`.
That will give us a new command `corneal controller Post` that can be used to generate controllers independently.
## Todo
- [x] Call ModelGenerator programmatically
- [x] Create ControllerGenerator `$ corneal controller Post`
- [x] Call ControllerGenerator programmatically

Let me know what you guys think.
Cheers. 👍

### CODE REVIEW

**Comment by achasveachas** [comment]
Awesome! I wanted to do that originally but I couldn't figure out how to invoke it `ModelGenerator`...

**Comment by azemoh** [comment]
Cool! @achasveachas do you want to create the `ControllerGenerator`? since you are already familiar with it.

**Comment by achasveachas** [comment]
I'll see if I can get around to it. Don't want to promise anything.

**Comment by azemoh** [comment]
That's alright. I think it's a chance for someone else to contribute and learn from this.

**Comment by andela-jazemoh** [comment]
Hey guys, is anyone working on this? wanna know if I can finish it up.

**Comment by azemoh** [comment]
Hey guys, is anyone working on this? wanna know if I can finish it up.

**Comment by achasveachas** [comment]
I don't think I'll get a chance in the near future.

**Comment by achasveachas** [comment]
Maybe you can add an issue under the 'hacktoberfest' tag and see if any nice people on the internet want to help? :)

**Comment by azemoh** [comment]
Hey @thebrianemory we're good.

These are the new commands.

``` bash
Commands:
  corneal -v              # Show Corneal version number
  corneal help [COMMAND]  # Describe available commands or one specific command
  corneal new APP_PATH    # Creates a new Sinatra application
  corneal model NAME      # Generate a model
  corneal controller NAME # Generate a controller
  corneal scaffold NAME   # Generate a model with its associated views and controllers
```

The controller generator also have an optional views flag `--no-views` to create controllers without views.

**Comment by azemoh** [comment]
Any plans to review this @thebrianemory ?

**Comment by thebrianemory** [comment]
@azemoh Merged and uploaded to RubyGems. Waaayyyy overdue. Thank you so much for working on this!

**Pull request merged**
