### PR TITLE
added sqlite3 version specification, replaced double quotes with sing…

### PR DESCRIPTION
**Pull request by jonfoster9999**
This great gem stopped working for me yesterday, and the only way I could fix it was to add this sqlite3 version spec. I also fixed a double quote that was bugging me in the generator :D

### CODE REVIEW

**Comment by jonfoster9999** [comment]
Note, the error that I got that prompted this PR was when running the server and loading the app, I received in the browser:

```Boot Error
Something went wrong while loading config.ru

Gem::LoadError: Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
```

**Comment by AlexanderCleasby** [comment]
This fix workd for me thank you @jonfoster9999 !

**Comment by idev4u** [comment]
I had the same issue and I hope this PR will be merged soon :-)

**Comment by thebrianemory** [comment]
> This great gem stopped working for me yesterday, and the only way I could fix it was to add this sqlite3 version spec. I also fixed a double quote that was bugging me in the generator :D

Thank you for this PR, @jonfoster9999! I'll look at it this week, get it merged in, and get it published to RubyGems.

**Pull request merged**
